export const types = {
    // Sync
    FILL_POSTS:  'FILL_POSTS',
    CREATE_POST: 'CREATE_POST',
    DELETE_POST: 'DELETE_POST',
    CLEAR_POSTS: 'CLEAR_POSTS',
    LIKE_POST:   'LIKE_POST',

    // Async
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    DELETE_POST_ASYNC: 'DELETE_POST_ASYNC',
    LIKE_POST_ASYNC:   'LIKE_POST_ASYNC',
};
